apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedRegistries
metadata:
  name: registries-allowed
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - falco
  parameters:
    registries:
      - "docker.io"
      - "reg.kyverno.io"
      - "ghcr.io"
      - "docker.io/falcosecurity"
      - "falcosecurity"