---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-web-rolebinding
  namespace: app-web
subjects:
  - kind: ServiceAccount
    name: default
    namespace: app-web
roleRef:
  kind: Role
  name: app-web-role
  apiGroup: rbac.authorization.k8s.io
