apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdenynodeport
spec:
  crd:
    spec:
      names:
        kind: K8sDenyNodePort
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package denynodeport
        violation[{"msg": msg}] {
          svc := input.review.object
          svc.spec.type == "NodePort"
          msg := sprintf("Service %v cannot be NodePort", [svc.metadata.name])
        }
