---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: requiredresources
spec:
  crd:
    spec:
      names:
        kind: RequiredResources
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requiredresources
        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          not c.resources.limits
          msg := sprintf("Container %v must have resource limits", [c.name])
        }
