apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: mandatorylabels
spec:
  crd:
    spec:
      names:
        kind: MandatoryLabels
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requiredlabels
        violation[{"msg": msg}] {
          not input.review.object.metadata.labels.env
          msg := "Pod must have label 'env'"
        }
