---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-rules
  namespace: falco
data:
  falco_rules.yaml: |
    - rule: Write below etc
      desc: Detect writing to /etc
      condition: evt.type = open and fd.name startswith "/etc"
      output: "File below /etc opened (user=%user.name command=%proc.cmdline file=%fd.name)"
      priority: WARNING
