---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-nodeport
spec:
  validationFailureAction: enforce
  rules:
    - name: no-nodeport
      match:
        resources:
          kinds:
            - Service
      validate:
        message: "NodePort services are forbidden"
        pattern:
          spec:
            type: "!NodePort"
