---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-env-label
spec:
  validationFailureAction: enforce
  rules:
    - name: check-env-label
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "All pods must have the label 'env'"
        pattern:
          metadata:
            labels:
              env: "?*"
