name: CD - Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Set Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign Docker image
        run: |
          cosign sign ghcr.io/${{ github.repository }}/app-secure:latest \
            --key "${{ secrets.COSIGN_KEY }}"

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -k kubernetes/apps/

      - name: Check Policy Violations
        run: |
          kubectl get events --all-namespaces | grep -i "violation" && exit 1 || exit 0

      - name: Verify deployment
        run: |
          kubectl get pods -A
