name: CD - Deploy to Kubernetes

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-push-sign:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize repo name
        run: |
          IMAGE_REPO=$(echo "$IMAGE_REPO" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
          echo "IMAGE_REPO=$IMAGE_REPO" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t app-secure:latest  ./docker/app-web/

      - name: Push image
        run: |
          docker tag app-secure:latest ghcr.io/rasclevictor/k8s-secure/app-secure:latest
          docker push ghcr.io/rasclevictor/k8s-secure/app-secure:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign container image with Cosign Keyless via GitHub OIDC
        run: |
          cosign sign $IMAGE_REPO/app-secure:latest --yes
