---
name: CI - Build & Security Scan

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml

      - name: Install Kubeconform
        run: |
            curl -sSL -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
            tar -xzf kubeconform.tar.gz
            chmod +x kubeconform
            sudo mv kubeconform /usr/local/bin/kubeconform

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Kubeconform validation
        run: |
          find ./kubernetes -type f -name "*.yml" ! -path "./kubernetes/security/gatekeeper/values/values.yml" \
            | xargs kubeconform -strict -kubernetes-version 1.29.0 -ignore-missing-schemas

      - name: Build Docker image
        run: docker build -t app-secure:latest  ./docker/app-web/

      - name: Trivy - Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-secure:latest
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL

      - name: Trivy - Config Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: ./kubernetes
          exit-code: '0'
          format: table
          severity: HIGH,CRITICAL

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag app-secure:latest ghcr.io/rasclevictor/k8s-secure/app-secure:latest
          docker push ghcr.io/rasclevictor/k8s-secure/app-secure:latest
